export type {
  BaseModel,
  Tenant,
  User,
  Candidate,
  Instructor,
  Category,
  Vehicle,
  Country,
  Municipality,
  Place,
  Payment,
  TheoryHourSession,
  PracticalHourSession,
  LessonChapter,
  ScheduledLesson,
  CandidateTest,
  Verification,
  Expense,
  ExpenseType,
  InstructorPayment,
  SupplementaryRegistration,
  Conversation,
  LastMessagePreview,
  Message,
  AuditLog,
  Exam,
  ExamEligibility,
} from './models';

export type {
  ApiResponse,
  ApiError,
  PaginatedResponse,
  PaginatedData,
  RecentCandidate,
  DashboardStats,
  CategoryBreakdown,
  DashboardAlert,
  PaymentSummary,
  ExpenseSummary,
  InstructorDebtSummary,
  InstructorDashboard,
  LoginRequest,
  LoginResponse,
  RefreshResponse,
  GlobalStats,
} from './api';
